# Generated by Django 3.0.10 on 2020-10-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0162_remove_seat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCBTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('state', models.CharField(default='created', max_length=16)),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scb_transaction', to='pretixbase.OrderPayment')),
            ],
        ),
    ]
